[package]
name = "mini_rust_parser"
version = "0.1.0"
authors = ["Julie Rymer <rymerjulie.pro@gmail.com>"]
edition = "2018"


[dependencies]
clap = {version = "~2.33.1", default-features = false}
log = "~0.4.8"
env_logger = "~0.7.1"
serde_json = "~1.0.53"
term-table = "~1.3.0"
